services:
  liph-bank.service.postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - ./docker/storage/pgdata:/var/lib/postgresql/data
